services:
  smarthome:
    image: vladimirovsk/smarthome:latest
    platform: linux/arm64
#    build:
#      context: .
#      dockerfile: Dockerfile
    command: ['npm', 'run', 'start:prod']
    container_name: smarthome
    restart: no
    ports:
      - '8000:8000'
    networks:
      - bitcoders

networks:
  bitcoders:
    driver: bridge
