version: '3'
services:
  smarthome:
    image: vladimirovsk/smarthome:latest
    #build:
    #  context: .
    command: ['npm', 'run', 'start']
    container_name: smarthome
    restart: no
    ports:
      - '8000:8000'
    networks:
      - bitcoders

networks:
  bitcoders:
    driver: bridge
